jwt:
  secret_key: ${JWT_SECRET_KEY}
  expiration_time_minutes: ${JWT_EXPIRATION_TIME_MINUTES}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}

app:
  port: ${APP_PORT}
  debug: ${APP_DEBUG}

authentication:
  domain: ${AUTH0_DOMAIN}
  client_id: ${AUTH0_CLIENT_ID}
  client_secret: ${AUTH0_CLIENT_SECRET}
  callback: ${AUTH0_CALLBACK_URL}